services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    restart: "no"
    env_file:
      - ../.env
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: "no"
    env_file:
      - ../.env
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: "no"
    env_file:
      - ../.env
    depends_on:
      - mongo
    ports:
      - 8081:8081    
    
